// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_cognito_identity_pool_id": "us-west-2:ad496b53-cdaf-4469-859d-92e4cc9c2ce2",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_RQSNgejQl",
    "aws_user_pools_web_client_id": "7nvs3aotfeq9guq34qmleqgis3",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://cc7estiytvcyhgewracovb7cym.appsync-api.us-west-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-west-2",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
