// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_cognito_identity_pool_id": "us-west-2:bcf553da-c4f1-4ccc-9de2-7766cceb1e6e",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_aA8FxkOsT",
    "aws_user_pools_web_client_id": "7r01i1gte2h5dm7onij5b20ne8",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://vtgebvb5trdltdyaepdaaigsjq.appsync-api.us-west-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-west-2",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
